get:
  tags:
    - Product
  operationId: getProductById
  parameters:
    - name: id
      in: path
      required: true
      schema:
        type: integer
        format: int64
  responses:
    "200":
      description: OK
      content:
        application/hal+json:
          schema:
            allOf:
              - $ref: "../../components/responses/v1/ResponseDTO.yaml"
              - type: object
                properties:
                  data:
                    $ref: "../../components/schemas/v1/response/ProductResponseDTO.yaml"
    "404":
      description: Not Found
      content:
        application/json:
          schema:
            $ref: "../../components/responses/Problem.yaml"

put:
  tags:
    - Product
  operationId: updateProduct
  parameters:
    - name: id
      in: path
      required: true
  requestBody:
    content:
      application/json:
        schema:
          $ref: "../../components/schemas/v1/request/ProductRequestDTO.yaml"
    required: true
  responses:
    "201":
      description: Created
      content:
        application/hal+json:
          schema:
            allOf:
              - $ref: "../../components/responses/v1/ResponseDTO.yaml"
              - type: object
                properties:
                  data:
                    $ref: "../../components/schemas/v1/request/ProductRequestDTO.yaml"
    "400":
      description: Bad Request
      content:
        application/json:
          schema:
            $ref: "../../components/responses/Problem.yaml"
    "404":
      description: Not Found
      content:
        application/json:
          schema:
            $ref: "../../components/responses/Problem.yaml"
    "409":
      description: Conflict
      content:
        application/json:
          schema:
            $ref: "../../components/responses/Problem.yaml"


delete:
  tags:
    - Product
  operationId: deleteProduct
  parameters:
    - name: id
      in: path
      required: true
      schema:
        type: integer
        format: int64
  responses:
    "204":
      description: No Content

    "404":
      description: Not Found
      content:
        application/json:
          schema:
            $ref: "../../components/responses/Problem.yaml"