get:
  tags:
    - Product
  operationId: getProductById
  parameters:
    - name: id
      in: path
      required: true
      schema:
        type: integer
        format: int64
  responses:
    "200":
      description: OK
      content:
        application/hal+json:
          schema:
            allOf:
              - $ref: "../../components/responses/v1/ResponseDTO.yaml"
              - type: object
                properties:
                  data:
                    $ref: "../../components/schemas/v1/response/ProductResponseDTO.yaml"
    "404":
      description: Not Found
      content:
        application/json:
          schema:
            $ref: "../../components/responses/Problem.yaml"
delete:
  tags:
    - Product
  operationId: deleteProduct
  parameters:
    - name: id
      in: path
      required: true
      schema:
        type: integer
        format: int64
  responses:
    "204":
      description: No Content
      content:
        application/hal+json:
          schema:
            $ref: "../../components/responses/v1/ResponseDTO.yaml"
    "404":
      description: Not Found
      content:
        application/json:
          schema:
            $ref: "../../components/responses/Problem.yaml"