type: object
properties:
  saleId:
    type: integer
    format: int64
  productId:
    type: integer
    format: int64
  quantityReturned:
    type: integer
    format: int32
    minimum: 0
    exclusiveMinimum: true
  reason:
    type: string

required:
  - saleId
  - productId
  - quantityReturned