type: object
properties:
  id:
    type: integer
    format: int64
  customer:
    $ref: "CustomerDTO.yaml"
  product:
    $ref: "ProductDTO.yaml"
  quantityReturned:
    type: integer
    format: int32
  reason:
    type: string
required:
  - id
  - product
  - quantityReturned