get:
  tags:
    - ProductReturn
  operationId: getAllProductReturns
  parameters:
    - name: page
      in: query
      required: false
      schema:
        type: integer
        format: int32
        default: 0
    - name: size
      in: query
      required: false
      schema:
        type: integer
        format: int32
        default: 10
  responses:
    "200":
      description: OK
      content:
        application/hal+json:
          schema:
            $ref: "../../components/responses/v1/PaginatedResponseDTOProductReturnDTO.yaml"

post:
  tags:
    - ProductReturn
  operationId: addProductReturn
  requestBody:
    content:
      application/json:
        schema:
          $ref: "../../components/schemas/v1/ProductReturnCreateDTO.yaml"
    required: true
  responses:
    "201":
      description: Created
      content:
        application/hal+json:
          schema:
            $ref: "../../components/Responses/v1/ResponseDTOProductReturnDTO.yaml"
    "400":
      description: Bad Request
      content:
        application/json:
          schema:
            $ref: "../../components/responses/Problem.yaml"
    "409":
      description: Conflict
      content:
        application/json:
          schema:
            $ref: "../../components/responses/Problem.yaml"